# Generated by Django 5.0.6 on 2024-06-11 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eccomerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
